### ISSUE TITLE
能否考虑移植到iCESugar运行

### ISSUE THREAD

**Issue by wuxx** [liangkangnan/tinyriscv#3]
强烈支持此项目，我也是嵌入式工程师，正在学习RISC-V中，因方便自己学习制作了开源的iCESugar开发板
https://github.com/wuxx/icesugar
可以使用完全开源的工具链（yosys & nextpnr & icestorm）在Linux下开发，能否考虑移植tinyriscv到iCESugar上运行呢

**Comment by liangkangnan** [comment]
这个板子我之前有看过。移植tinyriscv的话资源是不够的，至少要10000LUT。

**Comment by liangkangnan** [comment]
你可以考虑做一块xilinx artix-7的开发板，会有需求的。

**Comment by wuxx** [comment]
好的，后期可能会做一小批ULX3S，是硬件开源的开发板，资源比较丰富
https://github.com/emard/ulx3s

**Comment by liangkangnan** [comment]
可以，等有板子卖了我移植上去。

**Comment by liangkangnan** [comment]
建议板子上做两块SPI Flash，一块用来放FPGA配置文件，一块用来放移植软核后的C语言程序。

**Comment by liangyongxiang** [comment]
所以有板子了吗？

**Comment by wuxx** [comment]
ulx3s暂时不准备做了，目前偶然发现深圳卡莱特公司的5A-75B和i5系列模组都是基于lattice ECP5 LFE5U-25F的，有24K的LUT，带8MB SDRAM，两个千M网卡，可以用开源工具链开发，而且价格很便宜（一百以内），ECP5系列开源社区资料很多，可玩性很高，我已经逆向出了所有IO引脚，后面可能会考虑做一批i5的底板。

https://github.com/wuxx/Colorlight-FPGA-Projects
chubby75
https://github.com/q3k/chubby75
Colorlight-5A-75B
https://github.com/kholia/Colorlight-5A-75B
ulx3s_examples by lawrie
https://github.com/lawrie/ulx3s_examples
ULX3S-Blinky by DoctorWkt
https://github.com/DoctorWkt/ULX3S-Blinky

**Comment by liangyongxiang** [comment]
> ulx3s暂时不准备做了，目前偶然发现深圳卡莱特公司的5A-75B和i5系列模组都是基于lattice ECP5 LFE5U-25F的，有24K的LUT，带8MB SDRAM，两个千M网卡，可以用开源工具链开发，而且价格很便宜（一百以内），ECP5系列开源社区资料很多，可玩性很高，我已经逆向出了所有IO引脚，后面可能会考虑做一批i5的底板。
> 
> https://github.com/wuxx/Colorlight-FPGA-Projects
> chubby75
> https://github.com/q3k/chubby75
> Colorlight-5A-75B
> https://github.com/kholia/Colorlight-5A-75B
> ulx3s_examples by lawrie
> https://github.com/lawrie/ulx3s_examples
> ULX3S-Blinky by DoctorWkt
> https://github.com/DoctorWkt/ULX3S-Blinky

嗯，如果你准备做底板，考虑底板和模组打包卖吗？我想来一套。

**Comment by wuxx** [comment]
OK，近期应该会推出，有进展我会留言

**Comment by wuxx** [comment]
生产了一小批底板，配套卡莱特的i5模组使用，感兴趣的可以点击购买，群内也有底板PCB源文件，可以自行打样
https://item.taobao.com/item.htm?spm=a1z10.3-c-s.w4002-21349689064.12.e624773d7nkgih&id=631164799875
